# Reference: https://github.com/dgraph-io/dgraph/blob/master/dgraph/docker-compose.yml
version: "3.4"
services:

  # Graph API
  api:
    image: doraboateng/graph-service:latest
    depends_on:
      - zero
      - alpha
    environment:
      API_PORT: "8810"
    ports:
      - "8810:8810"
    restart: on-failure

  # Dgraph Zero
  zero:
    image: dgraph/dgraph:v20.03.0
    command: >-
      dgraph zero
        --bindall
        --block_rate 10
        --expose_trace
        --logtostderr
        --my=zero:5080
        --profile_mode block
        -v=2
    restart: on-failure

  # Dgraph Alpha
  alpha:
    image: dgraph/dgraph:v20.03.0
    command: >-
      dgraph alpha
        --block_rate 10
        --expose_trace
        --logtostderr
        --lru_mb=1024
        --my=alpha:7080
        --profile_mode block
        --trace 1.0
        -v=2
        --zero=zero:5080
    depends_on:
      - zero
    restart: on-failure
