#!/usr/bin/env bash

# Exit on error
set -e

HELP="Use the \"help\" command to list available scripts."

# Determine which shell script to run.
SCRIPT_NAME=$1
if [ ! "$SCRIPT_NAME" ]; then
    EXEC="./scripts/start.sh"
elif [[ "$SCRIPT_NAME" == "help" ]]; then
    printf "Available scripts:\n\n"
    ls ./scripts
    printf "\n%s\n" "$HELP"
    exit 0
elif [ "$SCRIPT_NAME" = "ratel" ]; then
    echo "Dgraph Ratel: http://localhost:8812"
    exit 0
elif [[ "$SCRIPT_NAME" =~ .*\.sh ]]; then
    EXEC="./scripts/$SCRIPT_NAME"
else
    EXEC="./scripts/$SCRIPT_NAME.sh"
fi

# Make sure shell script is valid.
if [ ! -x "$EXEC" ]; then
    echo "\"$SCRIPT_NAME\" is not a valid command. $HELP"
    exit 1
fi

$EXEC "${@:2}"
