name: Build and Publish Docker Image

on:
  push:
    branches: [stable]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        repository: doraboateng/graph
        username: dorabot
        password: ${{ secrets.DOCKER_TOKEN }}
        # push: ${{ startsWith(github.ref, 'refs/tags/') }}
        push: false
        tag_with_ref: true
        tags: latest
        target: prod
